### ISSUE TITLE
Crash with Close Content

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/yabause#45]
It's crashing RetroArch with Close Content

Ubuntu 18.04, gcc 7.3.0

```
The futex facility returned an unexpected error code.[New Thread 0x7fffc9d54700 (LWP 10524)]

Thread 3 "retroarch" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffdc455700 (LWP 10433)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
(gdb) 
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 0, 140736888916656, 140737333943424, 140736888916528, 140737351960330, 140736892786304, 140737336140576, 140736892786264, 140736892786264, 0, 0, 
            18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fffefa0c801 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 2, 0 <repeats 12 times>, 140736888916128, 140736888916320}}, 
          sa_flags = 4096, sa_restorer = 0x6}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#2  0x00007fffefa555e5 in __libc_message (action=(do_abort | do_backtrace), fmt=0x7fffefb82796 "%s", fmt=0x7fffefb82796 "%s", action=(do_abort | do_backtrace))
    at ../sysdeps/posix/libc_fatal.c:181
        ap = {{gp_offset = 24, fp_offset = 0, overflow_arg_area = 0x7fffdc454970, reg_save_area = 0x7fffdc454910}}
        fd = <optimized out>
        list = 0x0
        nlist = 1
        cp = 0x7fffefb82798 ""
        written = <optimized out>
#3  0x00007fffefa5592a in __GI___libc_fatal (message=message@entry=0x7ffff6cd0180 "The futex facility returned an unexpected error code.") at ../sysdeps/posix/libc_fatal.c:191
No locals.
#4  0x00007ffff6cc9aea in futex_fatal_error () at ../sysdeps/nptl/futex-internal.h:200
No locals.
#5  futex_wake (private=<optimized out>, processes_to_wake=<optimized out>, futex_word=<optimized out>) at ../sysdeps/unix/sysv/linux/futex-internal.h:247
        res = <optimized out>
        res = <optimized out>
        __ret = <optimized out>
        resultvar = <optimized out>
        __arg4 = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a4 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
#6  __condvar_confirm_wakeup (private=<optimized out>, cond=<optimized out>) at pthread_cond_wait.c:55
No locals.
#7  __pthread_cond_wait_common (abstime=0x0, mutex=0x7fffdc805658, cond=0x7fffdc805680) at pthread_cond_wait.c:419
        err = <optimized out>
        g = 0
        flags = <optimized out>
        g1_start = <optimized out>
        signals = <optimized out>
        result = <optimized out>
        wseq = <optimized out>
        seq = 462
        private = <optimized out>
        maxspin = <optimized out>
        err = <optimized out>
        result = <optimized out>
        wseq = <optimized out>
        g = <optimized out>
        seq = <optimized out>
        flags = <optimized out>
        private = <optimized out>
        signals = <optimized out>
        g1_start = <optimized out>
        spin = <optimized out>
        buffer = <optimized out>
        cbuffer = <optimized out>
        rt = <optimized out>
        s = <optimized out>
#8  __pthread_cond_wait (cond=0x7fffdc805680, mutex=0x7fffdc805658) at pthread_cond_wait.c:655
No locals.
#9  0x00007fffdc4c7d1d in ?? ()
No symbol table info available.
#10 0x00000070000000e0 in ?? ()
No symbol table info available.
#11 0x00007fffdc805638 in ?? ()
No symbol table info available.
#12 0x00007fffdc454a80 in ?? ()
No symbol table info available.
#13 0x00007fffdc4c431c in ?? ()
No symbol table info available.
#14 0x00007fffdc454ab0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by barbudreadmon** [comment]
Is it still happening ? I would expect threading code to work properly after i re-implemented it.

**Comment by barbudreadmon** [comment]
Closing, re-open if the issue persist.
